name: CI-CD

on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npx yarn
    - name: Build
      run: npx yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: assets
        path: dist
  #test:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Install dependencies
  #    run: yarn    
  #  - name: Run Lint Checks
  #    run: yarn style
  unittest:
    runs-on: ubuntu-latest.                 # this job will run on the latest version of Ubuntu
    steps:                                  # list of steps that need to be taken when Unit Tests is triggered 
    - uses: actions/checkout@v3             # check out code from repository
    - name: Install dependencies            # install all dependencies needed for Unit Tests (ex. Jest) 
      run: npx yarn    
    - uses: actions/download-artifact@v3    # download compiled code from build and make it available for Unit Tests 
      with:
        path: dist
    - name: Run Unit Tests                  # run Unit Tests using Jest
      run: npx yarn test
